services:

  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: api
    networks:
      - wms
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/nextjs/Dockerfile
      target: prod
    container_name: frontend
    environment:
      - NODE_ENV=production
    networks:
      - wms

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - frontend
    networks:
      - wms

  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - wms

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - wms

networks:
  wms:

volumes:
  pgsql_data:
  pgadmin_data: